# Generated by Django 3.1.3 on 2020-11-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImgModel',
            new_name='Image',
        ),
    ]
