# Generated by Django 3.1.3 on 2020-11-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0004_auto_20201130_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='dob',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='pan',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
