# Generated by Django 3.1.3 on 2020-11-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcard', '0005_auto_20201130_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='image_id',
            field=models.IntegerField(),
        ),
    ]
